# Generated by Django 5.2.3 on 2025-07-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_member_birth_date_member_email_member_gener"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="gener",
            new_name="gender",
        ),
    ]
